/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "../interface.h"

void *
moverobot_1_svc(MoveRequest arg1,  struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

WorldStatus *
getstatus_1_svc(struct svc_req *rqstp)
{
	static WorldStatus  result;

	/*
	 * insert server code here
	 */

	return &result;
}
