/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../interface.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void *
_moverobot_1 (MoveRequest  *argp, struct svc_req *rqstp)
{
	return (moverobot_1_svc(*argp, rqstp));
}

static WorldStatus *
_getstatus_1 (void  *argp, struct svc_req *rqstp)
{
	return (getstatus_1_svc(rqstp));
}

static void
simulation_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		MoveRequest moverobot_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case MoveRobot:
		_xdr_argument = (xdrproc_t) xdr_MoveRequest;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) _moverobot_1;
		break;

	case GetStatus:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_WorldStatus;
		local = (char *(*)(char *, struct svc_req *)) _getstatus_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SIMULATION, SIMULATION_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SIMULATION, SIMULATION_VERSION, simulation_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SIMULATION, SIMULATION_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SIMULATION, SIMULATION_VERSION, simulation_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SIMULATION, SIMULATION_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
