/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface.h"

bool_t
xdr_ObjectType (XDR *xdrs, ObjectType *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Object (XDR *xdrs, Object *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_ObjectType (xdrs, &objp->type))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->x))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->m))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fuel))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->x);
			IXDR_PUT_LONG(buf, objp->y);
			IXDR_PUT_LONG(buf, objp->m);
			IXDR_PUT_LONG(buf, objp->id);
			IXDR_PUT_LONG(buf, objp->fuel);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_ObjectType (xdrs, &objp->type))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->x))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->m))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fuel))
				 return FALSE;
		} else {
			objp->x = IXDR_GET_LONG(buf);
			objp->y = IXDR_GET_LONG(buf);
			objp->m = IXDR_GET_LONG(buf);
			objp->id = IXDR_GET_LONG(buf);
			objp->fuel = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_ObjectType (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->m))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->fuel))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_WorldStatus (XDR *xdrs, WorldStatus *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->objects.objects_val, (u_int *) &objp->objects.objects_len, MAXOBJECTS,
		sizeof (Object), (xdrproc_t) xdr_Object))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MoveRequest (XDR *xdrs, MoveRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->diffX))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->diffY))
		 return FALSE;
	return TRUE;
}
