/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACE_H_RPCGEN
#define _INTERFACE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum ObjectType {
	ROBOT = 0,
	FUEL_SOURCE = 1,
};
typedef enum ObjectType ObjectType;

struct Object {
	enum ObjectType type;
	int x;
	int y;
	int m;
	int id;
	int fuel;
};
typedef struct Object Object;
#define MAXOBJECTS 100

struct WorldStatus {
	struct {
		u_int objects_len;
		Object *objects_val;
	} objects;
};
typedef struct WorldStatus WorldStatus;

struct MoveRequest {
	int id;
	int diffX;
	int diffY;
};
typedef struct MoveRequest MoveRequest;

#define SIMULATION 0x20000001
#define SIMULATION_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define MoveRobot 1
extern  void * moverobot_1(MoveRequest , CLIENT *);
extern  void * moverobot_1_svc(MoveRequest , struct svc_req *);
#define GetStatus 2
extern  WorldStatus * getstatus_1(CLIENT *);
extern  WorldStatus * getstatus_1_svc(struct svc_req *);
extern int simulation_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MoveRobot 1
extern  void * moverobot_1();
extern  void * moverobot_1_svc();
#define GetStatus 2
extern  WorldStatus * getstatus_1();
extern  WorldStatus * getstatus_1_svc();
extern int simulation_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ObjectType (XDR *, ObjectType*);
extern  bool_t xdr_Object (XDR *, Object*);
extern  bool_t xdr_WorldStatus (XDR *, WorldStatus*);
extern  bool_t xdr_MoveRequest (XDR *, MoveRequest*);

#else /* K&R C */
extern bool_t xdr_ObjectType ();
extern bool_t xdr_Object ();
extern bool_t xdr_WorldStatus ();
extern bool_t xdr_MoveRequest ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACE_H_RPCGEN */
