/*
 * Automatically generated by jrpcgen 1.0.7 on 13.06.2017
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

using System.Net;

/**
 * The class <code>interfaceClient</code> implements the client stub proxy
 * for the SIMULATION remote program. It provides method stubs
 * which, when called, in turn call the appropriate remote method (procedure).
 */
public class interfaceClient : OncRpcClientStub {

    /**
     * Constructs a <code>interfaceClient</code> client stub proxy object
     * from which the SIMULATION remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public interfaceClient(IPAddress host, int protocol) :         base(host, interface.SIMULATION, 1, 0, protocol) {
    }

    /**
     * Constructs a <code>interfaceClient</code> client stub proxy object
     * from which the SIMULATION remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param port Port number at host where the remote program can be reached.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public interfaceClient(IPAddress host, int port, int protocol) :        base(host, interface.SIMULATION, 1, port, protocol) {
    }

    /**
     * Constructs a <code>interfaceClient</code> client stub proxy object
     * from which the SIMULATION remote program can be accessed.
     * @param client ONC/RPC client connection object implementing a particular
     *   protocol.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public interfaceClient(OncRpcClient client) : base(client) {
    }

    /**
     * Constructs a <code>interfaceClient</code> client stub proxy object
     * from which the SIMULATION remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param program Remote program number.
     * @param version Remote program version number.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public interfaceClient(IPAddress host, int program, int version, int protocol) :        base(host, program, version, 0, protocol) {
    }

    /**
     * Constructs a <code>interfaceClient</code> client stub proxy object
     * from which the SIMULATION remote program can be accessed.
     * @param host Internet address of host where to contact the remote program.
     * @param program Remote program number.
     * @param version Remote program version number.
     * @param port Port number at host where the remote program can be reached.
     * @param protocol {@link org.acplt.oncrpc.OncRpcProtocols Protocol} to be
     *   used for ONC/RPC calls.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public interfaceClient(IPAddress host, int program, int version, int port, int protocol) :        base(host, program, version, port, protocol) {
    }

    /**
     * Call remote procedure MoveRobot_1.
     * @param arg1 parameter (of type MoveRequest) to the remote procedure call.
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public void MoveRobot_1(MoveRequest arg1) {
        XdrVoid result_ = XdrVoid.XDR_VOID;
        client.call(interface.MoveRobot_1, interface.SIMULATION_VERSION, arg1, result_);
    }

    /**
     * Call remote procedure GetStatus_1.
     * @return Result from remote procedure call (of type WorldStatus).
     * @throws OncRpcException if an ONC/RPC error occurs.
     * @throws IOException if an I/O error occurs.
     */
    public WorldStatus GetStatus_1() {
        XdrVoid args_ = XdrVoid.XDR_VOID;
        WorldStatus result_ = new WorldStatus();
        client.call(interface.GetStatus_1, interface.SIMULATION_VERSION, args_, result_);
        return result_;
    }

}
// End of interfaceClient.cs
