/*
 * Automatically generated by jrpcgen 1.0.7 on 13.06.2017
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "interface" ONC/RPC program.
 */
public class interface {
    public static readonly int SIMULATION_VERSION = 1;
    public static readonly int SIMULATION = 0x20000001;
    public static readonly int MAXOBJECTS = 100;
    public static readonly int MoveRobot_1 = 1;
    public static readonly int GetStatus_1 = 2;
}
// End of interface.cs
