/*
 * Automatically generated by jrpcgen 1.0.7 on 13.06.2017
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class MoveRequest : XdrAble {
    public int id;
    public int diffX;
    public int diffY;

    public MoveRequest() {
    }

    public MoveRequest(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(id);
        xdr.xdrEncodeInt(diffX);
        xdr.xdrEncodeInt(diffY);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        id = xdr.xdrDecodeInt();
        diffX = xdr.xdrDecodeInt();
        diffY = xdr.xdrDecodeInt();
    }

}
// End of MoveRequest.cs
