/*
 * Automatically generated by jrpcgen 1.0.7 on 13.06.2017
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public class ObjectType {

    public static readonly int ROBOT = 0;
    public static readonly int FUEL_SOURCE = 1;

}
// End of ObjectType.cs
