/*
 * Automatically generated by jrpcgen 1.0.7 on 13.06.2017
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class Object : XdrAble {
    public int type;
    public int x;
    public int y;
    public int m;
    public int id;
    public int fuel;

    public Object() {
    }

    public Object(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(type);
        xdr.xdrEncodeInt(x);
        xdr.xdrEncodeInt(y);
        xdr.xdrEncodeInt(m);
        xdr.xdrEncodeInt(id);
        xdr.xdrEncodeInt(fuel);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        type = xdr.xdrDecodeInt();
        x = xdr.xdrDecodeInt();
        y = xdr.xdrDecodeInt();
        m = xdr.xdrDecodeInt();
        id = xdr.xdrDecodeInt();
        fuel = xdr.xdrDecodeInt();
    }

}
// End of Object.cs
