/*
 * Automatically generated by jrpcgen 1.0.7 on 13.06.2017
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class WorldStatus : XdrAble {
    public Object [] objects;

    public WorldStatus() {
    }

    public WorldStatus(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        { int _size = objects.Length; xdr.xdrEncodeInt(_size); for ( int _idx = 0; _idx < _size; ++_idx ) { objects[_idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        { int _size = xdr.xdrDecodeInt(); objects = new Object[_size]; for ( int _idx = 0; _idx < _size; ++_idx ) { objects[_idx] = new Object(xdr); } }
    }

}
// End of WorldStatus.cs
